name : First workflow
on : [push]

jobs :

  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
    - name: echo a string
      run: echo "Hello, world!"
    - name: Multiline run-shell-commands
      run: 
        node -v
        npm -v
  parallel-job-macos:
    runs-on: macos_latest
    steps:
     - name: View sw Version
       run: sw_vers
  dependant-job:
    runs-on : windows-lates
    needs : run-shell-commands
    steps:
      - name: echo a string
        run: Wripe-Ouput "Windows String"
      - name: Error Step
        run: doesnotexits  