name: Working Dirs & Shells
on: [push]
jobs: 
    display-wg-info-windows:
        runs-on: windows-latest
        defaults:
          run:
            shell: pwsh

        steps:
            - name: Display Working Directory & List Files
              run: |
               Get-Location
               dir
               echo $env:GITHUB_SHA
               echo $env:GITHUB_RESPOSITORY
               echo $env:GITHUB_WORKSPACE

            - name: Python Shell
              shell: python
              run: |
                 import platform
                 print(platform.processor())

    display-wg-info:
        runs-on: ubuntu-latest
        defaults:
            run:
              shell: bash
              #working_directory : /de/ed
        steps:
        - name: Display Working Directory & List Files
          run: |
           pwd
           ls -a 
           echo $GITHUB_SHA
           echo $GITHUB_RESPOSITORY
           echo $GITHUB_WORKSPACE
        - name: Change Working Dir
          working-directory: /home/runner
          run: pwd 
           
    
